CREATE TABLE IF NOT EXISTS checklist_iso9001 (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  punto VARCHAR(10) NOT NULL,
  estado VARCHAR(20) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES usuarios(id) ON DELETE CASCADE
);
